---
- name: Create config output directory
  file:
    path: "{{ config_output_directory }}"
    state: directory

- name: Generate ASR Configuration Files
  template:
    src: router_full.j2
    dest: "{{ config_output_directory }}/{{item.hostname}}.txt"
  with_items: '{{[podiosv1[0],podiosv2[0]]}}'
  run_once: true

- ios_template:
    host: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    src: "router_full.j2"
  with_items: '{{podiosv1}}'
  tags:
    - deploy
  when: inventory_hostname[-1] == "1"

- ios_template:
    host: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    src: "router_full.j2"
  with_items: '{{podiosv2}}'
  tags:
    - deploy
  when: inventory_hostname[-1] == "2"

- name: Generate ASR Configuration Files
  template:
    src: router_xml.j2
    dest: "{{ config_output_directory }}/{{item.hostname}}.txt"
  with_items: '{{[podiosv1[0],podiosv2[0]]}}'
  run_once: true

- ios_template:
    host: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    src: "router_full.j2"
  with_items: '{{podiosv1}}'
  tags:
    - xml_deploy
  when: inventory_hostname[-1] == "1"

- ios_template:
    host: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    src: "router_full.j2"
  with_items: '{{podiosv2}}'
  tags:
    - xml_deploy
  when: inventory_hostname[-1] == "2"