---

ntp3: 3.3.3.3
ntp4: 4.4.4.4

fabric:
  - tenant_name: DEVELOPMENT
    tenant_id: 103
    ints:
      - vlan_id: 3240
        name: "10_103_240_0-DATA"
        subnet: "10.103.240.0/24"
      - vlan_id: 3241
        name: "10_103_241_0-VOICE"
        subnet: "10.103.241.0/24"
  - tenant_name: IOT
    tenant_id: 102
    ints:
      - vlan_id: 2240
        name: "10_102_240_0-DATA"
        subnet: "10.102.240.0/24"
      - vlan_id: 2241
        name: "10_102_241_0-VOICE"
        subnet: "10.102.241.0/24"
  - tenant_name: EMPLOYEE
    tenant_id: 101
    ints:
      - vlan_id: 1240
        name: "10_101_240_0-DATA"
        subnet: "10.101.240.0/24"
      - vlan_id: 1241
        name: "10_101_241_0-VOICE"
        subnet: "10.101.241.0/24"
